# Generated by Django 3.2.4 on 2021-10-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.TextField(max_length=1000000),
        ),
    ]
